# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

#[[main]]
#  name = "Job Market Paper"
#  url = "#featured"
#  weight = 20

[[main]]
  name = "Publications"
  url = "#publication_list"
  weight = 30


[[main]]
  name = "Working papers"
  url = "#working_paper"
  weight = 40


[[main]]
  name = "Policy Work"
  url = "#Policy_work"
  weight = 50


#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
    name = "CV"
    #url = "https://arefiles.ucdavis.edu/uploads/filer_public/1e/57/1e57d37a-8217-4f6a-ad20-089895420473/cv_oscar_barriga_cabanillas.pdf"
    url = "files/CV_OBC.pdf"
    weight = 70
